---
label: Settings
hide_body: true
fields:
- type: boolean
  name: settings
  label: settings
- type: text
  name: form_url
  label: form_url
- type: number
  name: hubspot_portal_id
  label: hubspot_portal_id
- name: google_tag_manager
  type: text
  config:
    required: false
  label: google_tag_manager
- name: google_tag_manager_amp
  type: text
  config:
    required: false
  label: google_tag_manager_amp
- name: facebook_pixel
  type: text
  config:
    required: false
  label: facebook_pixel
- name: linkedin_pixel
  type: text
  config:
    required: false
  label: linkedin_pixel
- name: stripe_key
  type: text
  config:
    required: false
  label: stripe_key
- type: text
  name: acuity_scheduling_src
  label: acuity_scheduling_src
- type: datetime
  name: preapplication_form_guid
  label: preapplication_form_guid
- type: text
  name: application_form_guid
  label: application_form_guid
- type: text
  name: instructor_form_guid
  label: instructor_form_guid
- type: text
  name: corporate_trainings_form_guid
  label: corporate_trainings_form_guid
- type: text
  name: corporate_form_guid
  label: corporate_form_guid
- type: text
  name: diversity_form_guid
  label: diversity_form_guid
- type: text
  name: assignment_form_guid
  label: assignment_form_guid
- name: pdf_viewer_url
  type: text
  config:
    required: false
  label: pdf_viewer_url
  hidden: true
- type: textarea
  name: description
  label: description
- type: field_group
  name: navigation
  label: navigation
  fields:
  - type: field_group_list
    name: header
    label: header
    fields:
    - type: text
      name: title
      label: title
    - name: url
      type: text
      config:
        required: false
      label: url
    - name: class
      type: text
      config:
        required: false
      label: class
  - type: field_group_list
    name: footer
    label: footer
    fields:
    - type: text
      name: title
      label: title
    - type: text
      name: url
      label: url
- type: field_group_list
  name: courses
  label: courses
  fields:
  - type: text
    name: code
    label: code
  - type: text
    name: title
    label: title
  - type: text
    name: description
    label: description
  - type: text
    name: length
    label: length
  - type: list
    name: list
    label: list
- type: field_group_list
  name: tracks
  label: tracks
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: category
    label: category
  - type: text
    name: url
    label: url
- type: field_group_list
  name: schools
  label: schools
  fields:
  - type: text
    name: key
    label: key
  - type: boolean
    name: active
    label: active
  - type: text
    name: name
    label: name
  - type: field_group
    name: navigation
    label: navigation
    fields:
    - type: field_group_list
      name: header
      label: header
      fields:
      - type: text
        name: title
        label: title
      - name: url
        type: text
        config:
          required: false
        label: url
      - name: class
        type: text
        config:
          required: false
        label: class
    - name: footer
      type: field_group_list
      fields:
      - name: title
        type: text
        config:
          required: false
        label: title
      - name: url
        type: text
        config:
          required: false
        label: url
      config:
        min: 
        max: 
        labelField: 
      label: footer
  - type: text
    name: url
    label: url
  - name: logo
    type: file
    config:
      maxSize: 250
    label: logo
  - name: seal
    type: file
    config:
      maxSize: 250
    label: seal
  - type: number
    name: phone
    label: phone
    config:
      min: '10000000000'
      max: ''
      step: 
  - type: number
    name: callrail_company_id
    label: callrail_company_id
  - type: text
    name: google_analytics
    label: google_analytics
  - type: text
    name: reddit_pixel
    label: reddit_pixel
  - type: text
    name: eventbrite_id
    label: eventbrite_id
  - type: text
    name: contact_form_guid
    label: contact_form_guid
  - type: text
    name: cta_form_guid
    label: cta_form_guid
  - name: preapplication_form_guid
    type: text
    config:
      required: false
    label: preapplication_form_guid
  - type: text
    name: course_guide_form_guid
    label: course_guide_form_guid
  - type: text
    name: application_form_guid
    label: application_form_guid
  - type: text
    name: twitter
    label: twitter
  - type: text
    name: eventbrite
    label: eventbrite
  - name: acuity_scheduling_src
    type: text
    config:
      required: false
    label: acuity_scheduling_src
  - name: linkedin
    type: text
    config:
      required: false
    label: linkedin
  - type: text
    name: facebook
    label: facebook
  - type: text
    name: instagram
    label: instagram
  - type: file
    name: course_guide
    label: course_guide
  - name: course_guide_img
    type: file
    config:
      maxSize: 250
    label: course_guide_img
  - type: field_group_list
    name: locations
    label: locations
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: street
      label: street
    - type: text
      name: city
      label: city
    - type: text
      name: state
      label: state
    - type: number
      name: postal
      label: postal
    - type: text
      name: url
      label: url
  - name: announcement
    type: text
    config:
      required: false
    label: announcement
  - name: start_dates
    type: field_group_list
    fields:
    - name: location
      type: text
      config:
        required: false
      label: location
    - name: course
      type: text
      config:
        required: false
      label: course
    - name: date
      type: text
      config:
        required: false
      label: date
    - name: days
      type: text
      config:
        required: false
      label: days
    - name: time
      type: text
      config:
        required: false
      label: time
    - name: length
      type: text
      config:
        required: false
      label: length
    - name: price
      type: text
      config:
        required: false
      label: price
    config:
      min: 
      max: 
      labelField: date
    label: start_dates
  - name: primary_light_color
    type: color
    label: primary_light_color
    config:
      required: false
      color_format: RGB
  - name: primary_dark_color
    type: color
    label: primary_dark_color
    config:
      required: false
      color_format: RGB
  - name: secondary_light_color
    type: color
    label: secondary_light_color
    config:
      required: false
      color_format: RGB
  - name: secondary_dark_color
    type: color
    label: secondary_dark_color
    config:
      required: false
      color_format: RGB
  - name: hero_overlay_color
    type: color
    label: hero_overlay_color
    config:
      required: false
      color_format: RGB
  - name: tracks
    type: field_group_list
    fields:
    - name: name
      type: text
      config:
        required: false
      label: name
    - name: stripe_product_sku
      type: text
      config:
        required: false
      label: stripe_product_sku
    config:
      min: 
      max: 
      labelField: 
    label: tracks
  - type: field_group_list
    name: instructors
    label: instructors
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: gravatar_email
      label: gravatar_email
    - type: text
      name: linkedin
      label: linkedin
    - type: text
      name: title
      label: title
    - type: text
      name: campus
      label: campus
    - type: textarea
      name: bio
      label: bio
  - type: field_group_list
    name: team
    label: team
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: title
      label: title
    - type: text
      name: email
      label: email
    - type: textarea
      name: bio
      label: bio
    - type: field_group_list
      name: links
      label: links
      fields:
      - type: text
        name: link
        label: link
      - type: text
        name: icon
        label: icon
      - type: text
        name: hex
        label: hex
  - type: field_group_list
    name: tutors
    label: tutors
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: id
      label: id
    - type: list
      name: skills
      label: skills
    - type: text
      name: email
      label: email
    - type: list
      name: location
      label: location
    - type: text
      name: calendar
      label: calendar
    - type: text
      name: virtual
      label: virtual
    - type: text
      name: rocketchat
      label: rocketchat
    - name: gravatar_email
      type: text
      config:
        required: false
      label: gravatar_email
- type: field_group_list
  name: logos
  label: logos
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: width
    label: width
  - type: text
    name: height
    label: height
  - type: file
    name: src
    label: src
pages:
- settings.html
